### ISSUE TITLE
Ios gives issue "System resources unavailable"
I haved nfc usage description in info plist as well

### ISSUE THREAD

**Issue by adeel399** [EYALIN/community-cordova-plugin-nfc#1]

**Comment by adeel399** [comment]
Now i haved created here please help its already been late

**Comment by EYALIN** [comment]
@adeel399 I checked most of the NFC functions in IOS, and all seems ok.
in order for me to help you, please describe a little bit more about what you are doing. IOS version? cordova version? plugin version?

**Comment by adeel399** [comment]
> @adeel399 I checked most of the NFC functions in IOS, and all seems ok.
> in order for me to help you, please describe a little bit more about what you are doing. IOS version? cordova version? plugin version?

It's iPhone 14 pro, iOS 16.6
Latest plugin version . Ionic capacitor

**Comment by EYALIN** [comment]
wasn't aware it was the capacitor.
do you see any exceptions in "adb logcat" ?

**Comment by adeel399** [comment]
> > @adeel399 I checked most of the NFC functions in IOS, and all seems ok.
> > in order for me to help you, please describe a little bit more about what you are doing. IOS version? cordova version? plugin version?
> 
> It's iPhone 14 pro, iOS 16.6
> Latest plugin version . Ionic capacitor

Still awaiting

**Comment by EYALIN** [comment]
@adeel399 sorry for the delay, i was out of work for a while.
since the issue you have is with capacitor, it is more challenging for me to test it, since im using Cordova.

**Comment by EYALIN** [comment]
@adeel399 sorry for the delay, but we cannot test the capacitor as we don't have the environment.

it will be great if you can make a PR for this issue, and I can help you with it
