### ISSUE TITLE
-[NFCTagReaderSession _connectTag:error:]:739 Error Domain=NFCError Code=2 "Missing required entitlement" UserInfo={NSLocalizedDescription=Missing required entitlement}

### ISSUE THREAD

**Issue by 2cLionDonath** [EYALIN/community-cordova-plugin-nfc#2]
I get the following error message when I try to scan an NFC tag on iOS:

-[NFCTagReaderSession _connectTag:error:]:739 Error Domain=NFCError Code=2 "Missing required entitlement" UserInfo={NSLocalizedDescription=Missing required entitlement}

Im Using XCODE 15.1 on iOS 17.1.2, Cordova 10.0.0 and cordova-ios 6.3.0

Another question, is it possible to read ISO 7816 tags?

**Comment by EYALIN** [comment]
@2cLionDonath did you upgrade to the latest cordova and cordova-ios version ?

**Comment by EYALIN** [comment]
@2cLionDonath plugin was upgraded to 1.4.0

closing this ticket
